# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: TILs from Dan Nguyen
email: dansonguyen@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A little blog where I log the little things I've learned day to day, particularly in fields of data journalism and programming.
# baseurl: "/til" # the subpath of your site, e.g. /blog
url: "https://dannguyen.github.io/til"
twitter_username: dancow
github_username:  dannguyen

# Build settings
plugins:
  - jekyll-feed

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


defaults:
  - scope:
      path: "assets/images"
    values:
      image: true


collections:
  posts:
    output: true
    permalink: /posts/:slug
    layout: post


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
